### ISSUE TITLE
blocks.find search not spanning over neighbors and only doing linear search

### ISSUE THREAD

**Issue by Code7R** [TexZK/hexrec#17]
Hi,

thanks for this great package. I found some issues, though. The blocks.find method's documentation reads like it was done for applying binary search (just like locate_at() does). But this is apparently not the case, there is only a simple slow loop inside.

Also, the current implementation does not look into subsequent blocks. That's not a problem if you have applied merge() before but in case someone has forgotten this, the find operation might throw the exception incorrectly.

However, since the find() method is probably already in use by people, it might make sense to deprecate it and document its issue, and create an alternative method like "bin_find". Which would also return a list of block ids, not just one.

**Comment by TexZK** [comment]
Hi,

I'm planning to depcrecate the whole `hexrec.blocks` by the next release, to be replaced by the `bytesparse` package.
Indeed, the current implementation here on GitHub is almost ready for the next release, and should warn for deprecation.

So, please check if you can try by installing from the GitHub source code.
Being deprecated, I'm not planning to change `hexrec.blocks`. Also, as stated by the readme, its implementation is slow because I wanted it to be naively simple. Please check if `bytesparse` fits your needs, to that I can get some feedback.

**Comment by Code7R** [comment]
Okay. `bytesparse` looks interesting at the fist glance but I get mixed feelings. Have only checked the accessible API so far. That raised questions...
- how to load and store hex files? Something like: `bytesparse.Memory.from_blocks(records.load_blocks())` or am I overlooking something?
- `union()` and `merge()` now removed. So if I have to overlay hex data from multiple sources, I do... what? `.write()`? That does not accept block sequences.

(more feedback next year, only mind-game with our usecases so far)

**Comment by TexZK** [comment]
I'll be referring to the current `hexrec` source code here on GitHub, which now uses the `bytesparse` package.

You can still call `hexrec.records.load_memory()` to load a hex file into a `bytesparse.Memory` object, as the latter is now replacing the deprecated `hexrec.blocks.Memory`.

About merging multiple sources, you can just load the files as `bytesparse.Memory` objects, and then `.write()` them onto a single `bytesparse.Memory` object:

```py
import hexrec.records as hr
import bytesparse

# For hexrec >= 0.3.0: Load all parts as independent bytesparse.Memory objects
m1 = hr.load_memory('part1.hex')
m2 = hr.load_memory('part2.hex')
m3 = hr.load_memory('part3.hex')

# For hexrec < 0.3.0 (as currently on PyPI):
m1 = bytesparse.Memory.from_blocks(hr.load_blocks('part1.hex'))
m2 = bytesparse.Memory.from_blocks(hr.load_blocks('part2.hex'))
m3 = bytesparse.Memory.from_blocks(hr.load_blocks('part3.hex'))

# Patch/overwrite m1 with data from m2 then m3,
# adding no offset to their record addresses
m1.write(0, m2)
m1.write(0, m3)

# Save merged data into a new file
hr.save_memory('merged.hex', m1)
```
