### ISSUE TITLE
hexrec.records.save_blocks always adding a dummy Linear Address Record

### ISSUE THREAD

**Issue by Code7R** [TexZK/hexrec#18]
Hi,

from what I see, when a user calls something like:

        save_blocks(out_res_path, blocks, record_type=IntelRecord, split_kwargs={"columns": columns})

The resulting file always contains an additional block which looks like:

:020000040000FA
:0400000500000000F7

From what I know about IntelHEX format, that is probably a Linear Address Record or Extended Linear Address Record. But those were not part of the data to store. They may have some purpose for somebody but in my usecase, they end up without contents.

So my wish would be to have a parameter of save_blocks to NOT add such dummy blocks unless there is data content for them, or maybe even make that behavior default.

**Comment by TexZK** [comment]
Yes that was added as a default option because some tools required them, thus the `hexrec.formats.intel.Record.terminate()` adds them automatically.
I agree that it should be made optional.

As a workaround, just remove those records by calling:

```py
block_list = list(save_blocks(<...>))
del block_list[-3:-1]
```
