### ISSUE TITLE
enum34 dependency is not compatible with Python 3.6 and later versions

### ISSUE THREAD

**Issue by cz6ace** [TexZK/hexrec#6]
Dependency to enum34 causes problems on Python >=3.6 e.g. using pyinstaller.
Ideally if "install_requires" in setup.py checks sys.version_info and only for python <3.6 it adds the num34.

**Comment by TexZK** [comment]
Ok sorry for the late answer, I've already removed Python 3.4 from the C.I., and I'm going to remove deprecated versions soon (including 2.7).
