### ISSUE TITLE
How to output s19 file per line data=32

### ISSUE THREAD

**Issue by liudulab** [TexZK/hexrec#7]
I try to input a s19 file and fill value, but output s19 file format was S315.... I except it is S325..

**Comment by TexZK** [comment]
Hi, are you using the command line interface (CLI), or the actual Python library?

Currently the CLI cannot specify the number of bytes per line. I guess I could add that parameter to the command line, if necessary.
The CLI is made for simple everyday operations, where **only the byte data content is important**. Metadata and formatting are **lost** while loading input.

If you are using the Python library, you can specify such parameter when writing the S19 file like in the following example:

```python
>>> import hexrec.records as hr
>>> memory = hr.load_memory('input.s19')
>>> fill_start, fill_endex, fill_byte = 0x4000, 0x4040, b'\xCC'
>>> memory.fill(fill_start, fill_endex, fill_byte)
>>> hr.save_memory('output.s19', memory, split_kwargs=dict(columns=32))
```

Currently, such operations are conservative only for byte data contents, while any metadata (header string, non-data records, etc.) are lost while loading.

Another way is to load the record file as actual records, and tweak the records themselves at your will. Of course, this method needs to work at record level, and comes at a much higher cost.
A brief example (not perfect, just to give a rough idea of the minimum complexity): 

```python
>>> import hexrec.records as hr
>>> records = hr.load_records('input.s19')
>>> header_data = records[0].data if records[0].tag == hr.MotorolaTag.HEADER else None
>>> fill_start, fill_endex, fill_byte = 0x4000, 0x4020, b'\xCC'
>>> records[4:4] = [hr.MotorolaRecord.build_data(fill_start, fill_byte * (fill_endex - fill_start))]
>>> data_records = hr.get_data_records(records)
>>> records2 = list(hr.MotorolaRecord.build_standalone(data_records, header=header_data))
>>> hr.save_records('output.s19', records2)
```

**Comment by liudulab** [comment]
thanks for your answer.
using split_kwargs=dict(columns=32) , the output file was my excepted for the actual Python library.
i suggest the CLI support specify the number of bytes per line and import config file, such as set some bytes value to address 
config file:
set 0x1234 to 0x4000
set 0xabcd to 0x5000
set 0x456 to  0x7000
